# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Yulia <ypoyarko@redhat.com>, 2011-2012
# Yulia <yulia.poyarkova@redhat.com>, 2013-2014
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-04-08 15:09+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2014-03-05 04:30-0500\n"
"Last-Translator: Jakub Filak <jfilak@redhat.com>\n"
"Language-Team: Russian (http://www.transifex.com/projects/p/gnome-abrt/"
"language/ru/)\n"
"Language: ru\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Zanata 3.7.1\n"

#: ../src/gnome-abrt:265
msgid "My"
msgstr "Мои"

#: ../src/gnome-abrt:268 ../src/gnome_abrt/views.py:135
msgid "System"
msgstr "Система"

#: ../src/gnome-abrt:288
msgid "_Preferences"
msgstr "_Параметры"

#: ../src/gnome-abrt:289
msgid "_ABRT Configuration"
msgstr "_Конфигурация ABRT"

#: ../src/gnome-abrt:290
msgid "_Report problem with ABRT"
msgstr "Сообщить об  _ошибке ABRT"

#: ../src/gnome-abrt:294
msgid "_About"
msgstr "_О программе"

#: ../src/gnome-abrt:295
msgid "_Quit"
msgstr "В_ыход"

#: ../src/gnome-abrt.desktop.in.h:1 ../src/gnome_abrt/views.py:257
msgid "Problem Reporting"
msgstr ""

#: ../src/gnome-abrt.desktop.in.h:2
msgid "View and report application crashes"
msgstr "Просмотреть сбои и создать отчет"

#: ../src/gnome-abrt.appdata.xml.in.h:1
msgid ""
"Collection of software tools designed for collecting, analyzing and "
"reporting of software issues."
msgstr ""
"Коллекция программ для сбора информации, анализа и создания отчетов об "
"ошибках."

#: ../src/gnome-abrt.appdata.xml.in.h:2
msgid ""
"Its main purpose is to ease the process of reporting an issue and finding a "
"solution."
msgstr ""

#: ../src/gnome_abrt/dbus_problems.py:89
#, python-brace-format
msgid "Can't add receiver of signal '{0}'on DBus system path '{1}': {2}"
msgstr "Не удалось добавить получателя сигнала  «{0}» по пути DBus «{1}»: {2}"

#: ../src/gnome_abrt/dbus_problems.py:102
#, python-brace-format
msgid "Can't connect to DBus system bus '{0}' path '{1}': {2}"
msgstr "Не удалось подключиться к системной шине DBus «{0}» (путь «{1}»): {2}"

#: ../src/gnome_abrt/dbus_problems.py:109
#, python-brace-format
msgid "Can't get interface '{0}' on path '{1}' in bus '{2}': {3}"
msgstr "Не удалось получить интерфейс «{0}» по пути «{1}» шины «{2}»: {3}"

#: ../src/gnome_abrt/dbus_problems.py:154
msgid "Can't chown problem '{0}' over DBus service: {1!s}"
msgstr "Невозможно изменить владельца «{0}» через DBus: {1!s}"

#: ../src/gnome_abrt/dbus_problems.py:170
msgid "Can't get problem data from DBus service: {0!s}"
msgstr "Не удалось получить данные об ошибке от службы DBus: {0!s}"

#: ../src/gnome_abrt/dbus_problems.py:181
msgid "Can't get list of problems from DBus service: {0!s}"
msgstr "Не удалось получить список ошибок от службы DBus: {0!s}"

#: ../src/gnome_abrt/dbus_problems.py:195
msgid "Can't delete problem over DBus service: {0!s}"
msgstr "Не удалось удалить проблему службы DBus: {0!s}"

#: ../src/gnome_abrt/dialogs.py:55
msgid "The description of problem is too short"
msgstr "Слишком короткое описание проблемы"

#: ../src/gnome_abrt/dialogs.py:56
msgid ""
"In order to get more useful reports we do not accept reports with the "
"description shorter than 10 letters."
msgstr ""
"Отчеты, в которых описание проблемы составляет меньше 10 знаков, не "
"принимаются."

#: ../src/gnome_abrt/dialogs.py:66
msgid "The summary of problem is too short"
msgstr "Слишком короткая сводка"

#: ../src/gnome_abrt/dialogs.py:67
msgid ""
"In order to get more useful reports we do not accept reports with the "
"summary shorter than 10 letters."
msgstr ""
"Отчеты, в которых сводка  составляет меньше 10 знаков, не принимаются."

#: ../src/gnome_abrt/dialogs.py:93
msgid "Problem description"
msgstr "Описание"

#: ../src/gnome_abrt/dialogs.py:101
msgid "Summary:"
msgstr "Сводка:"

#: ../src/gnome_abrt/dialogs.py:120
msgid "_Send"
msgstr "_Отправить"

#. Sets text but text is selected :)
#: ../src/gnome_abrt/dialogs.py:134
msgid "A problem with ABRT"
msgstr "Ошибка ABRT"

#: ../src/gnome_abrt/directory_problems.py:216
#, python-brace-format
msgid ""
"You have probably reached inotify's limit on the number of watches in '{0}'. "
"The limit can be increased by proper configuration of inotify. For more "
"details see man inotify(7). This event causes that you will not be notified "
"about changes in problem data happening outside of this application. This "
"event do not affect any other functionality."
msgstr ""
"Возможно, достигнуто ограничение inotify на число отслеживаемых объектов в "
"«{0}». Это ограничение можно увеличить в настройках inotify (см. справочную "
"страницу inotify(7)). В противном случае вы не сможете узнавать об "
"изменениях данных проблем, происходящих за пределами приложения. Другая "
"функциональность не будет затронута."

#: ../src/gnome_abrt/directory_problems.py:262
#, python-brace-format
msgid "Can't open directory: '{0}'"
msgstr "Не удалось открыть каталог: «{0}»"

#: ../src/gnome_abrt/oops.glade.h:1
msgid "_Delete"
msgstr "_Удалить"

#: ../src/gnome_abrt/oops.glade.h:2
msgid "Delete selected problems"
msgstr "Удалить выбранные"

#: ../src/gnome_abrt/oops.glade.h:3
msgid "_Report"
msgstr "_Отчет"

#: ../src/gnome_abrt/oops.glade.h:4
msgid "Submits selected problem"
msgstr "Отправляет отчет о выбранной проблеме"

#: ../src/gnome_abrt/oops.glade.h:5
msgid "Analy_ze"
msgstr "_Анализ"

#: ../src/gnome_abrt/oops.glade.h:6
msgid "Open selected problem for analysis"
msgstr "Открыть проблему для анализа"

#: ../src/gnome_abrt/oops.glade.h:7
msgid "D_etails"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:8
msgid "Show technical details"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:9
msgid "_All problems"
msgstr "_Все проблемы"

#: ../src/gnome_abrt/oops.glade.h:10
msgid "Show all known problems from all system users"
msgstr "Показать проблемы для всех пользователей"

#: ../src/gnome_abrt/oops.glade.h:11
msgid "_Open problem's data directory"
msgstr "_Открыть каталог проблемы"

#: ../src/gnome_abrt/oops.glade.h:12
msgid ""
"Opens the selected problem's data directory in the default file system "
"browser"
msgstr "Открывает каталог данных выбранной проблемы в менеджере файлов"

#: ../src/gnome_abrt/oops.glade.h:13
msgid "_Copy problem's ID to Clipboard"
msgstr "_Скопировать ID ошибки в буфер"

#: ../src/gnome_abrt/oops.glade.h:14
msgid "Stores the selected problem's ID in Clibpoard"
msgstr "Копирует идентификатор выбранной проблемы в буфер обмена"

#: ../src/gnome_abrt/oops.glade.h:15
msgid "_Filter"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:16
msgid "Show filter box"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:17
msgid "Name"
msgstr "Имя"

#: ../src/gnome_abrt/oops.glade.h:18
msgid "Version"
msgstr "Версия"

#: ../src/gnome_abrt/oops.glade.h:19
msgid "Detected"
msgstr "Обнаружено"

#: ../src/gnome_abrt/oops.glade.h:20
msgid "<a href=\"https://glade.gnome.org/\">Very long placeholder URL tile</a>"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:21
msgid "<a href=\"https://github.com/abrt/gnome-abrt\">Placeholder URL</a>"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:22 ../src/gnome_abrt/views.py:875
msgid "Reported"
msgstr "Отправлено"

#: ../src/gnome_abrt/oops.glade.h:23
msgid "button"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:24
msgid "No problems detected!"
msgstr "Ошибки не обнаружены."

#: ../src/gnome_abrt/oops.glade.h:25
msgid "No source selected!"
msgstr "Источник не выбран."

#: ../src/gnome_abrt/oops.glade.h:26
msgid "No source"
msgstr "Нет источника"

#: ../src/gnome_abrt/problems.py:467
#, python-brace-format
msgid "Not found in cache but deleted: {0}"
msgstr "Не найдено в кэше, но удалено: {0}"

#: ../src/gnome_abrt/tools.py:34
msgid "Future"
msgstr "В будущем"

#: ../src/gnome_abrt/tools.py:41
msgid "Yesterday"
msgstr "Вчера"

#: ../src/gnome_abrt/tools.py:50
#, python-brace-format
msgid "Last week"
msgid_plural "{0:d} weeks ago"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../src/gnome_abrt/tools.py:53
#, python-brace-format
msgid "Last month"
msgid_plural "{0:d} months ago"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../src/gnome_abrt/tools.py:56
#, python-brace-format
msgid "Last year"
msgid_plural "{0:d} years ago"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../src/gnome_abrt/views.py:283
msgid "Failed to load UI definition"
msgstr "Не удалось загрузить определение интерфейса пользователя."

#: ../src/gnome_abrt/views.py:818
msgid "Unexpected system error"
msgstr ""

#: ../src/gnome_abrt/views.py:820
msgid "The system has encountered a problem and recovered."
msgstr ""

#: ../src/gnome_abrt/views.py:823
msgid "Fatal system failure"
msgstr ""

#: ../src/gnome_abrt/views.py:825
msgid "The system has encountered a problem and could not continue."
msgstr ""

#: ../src/gnome_abrt/views.py:838
#, python-brace-format
msgid "{0} problem has been detected"
msgstr "Обнаружена {0} проблема."

#: ../src/gnome_abrt/views.py:842
#, python-brace-format
msgid "{0} quit unexpectedly"
msgstr ""

#: ../src/gnome_abrt/views.py:845
msgid "The application encountered a problem and could not continue."
msgstr ""

#: ../src/gnome_abrt/views.py:848 ../src/gnome_abrt/views.py:850
msgid "N/A"
msgstr "нет"

#: ../src/gnome_abrt/views.py:878
msgid "cannot be reported"
msgstr "не может быть добавлен в отчет"

#: ../src/gnome_abrt/views.py:883
msgid "Reports"
msgstr "Отчеты"

#: ../src/gnome_abrt/views.py:889
msgid ""
"This problem has been reported, but a <i>Bugzilla</i> ticket has not been "
"opened. Our developers may need more information to fix the problem.\n"
"Please consider also <b>reporting it</b> to Bugzilla in order to provide "
"that. Thank you."
msgstr ""
"Для этой ошибки нет отчета в <i>Bugzilla</i>. Чтобы помочь разработчикам, "
"создайте отчет. Спасибо!"

#: ../src/gnome_abrt/views.py:894
msgid "yes"
msgstr "да"

#: ../src/gnome_abrt/views.py:896
msgid "no"
msgstr "нет"

#: ../src/gnome_abrt/controller.py:78
msgid ""
"Failed to execute the requested action because of an error in new process "
"creation"
msgstr "Не удалось выполнить действие: ошибка при создании нового процесса."
